### ISSUE TITLE
Unknown job state, exiting 3

### ISSUE THREAD

**Issue by laughingman7743** [GoogleCloudPlatform/flink-on-k8s-operator#252]
I'm running a streaming job, but sometimes the job restarts with `Unknown job state, exiting 3`. Often occurs in jobs that have been running for longer than a day.

```
Waiting for job to finish...
Waiting for response...
------------------ Running/Restarting Jobs -------------------
30.05.2020 07:11:24 : 3d40ed91bc55f4d199d2d3f44b6c549f : com.xxx.yyy.zzz.streaming.Main$ (RUNNING)
--------------------------------------------------------------
No scheduled jobs.
30.05.2020 07:11:24 : 3d40ed91bc55f4d199d2d3f44b6c549f : com.xxx.yyy.zzz.streaming.Main$ (RUNNING)

Found an active job.

Waiting for job to finish...
Waiting for response...
------------------ Running/Restarting Jobs -------------------
30.05.2020 07:11:24 : 3d40ed91bc55f4d199d2d3f44b6c549f : com.xxx.yyy.zzz.streaming.Main$ (RUNNING)
--------------------------------------------------------------
No scheduled jobs.
30.05.2020 07:11:24 : 3d40ed91bc55f4d199d2d3f44b6c549f : com.xxx.yyy.zzz.streaming.Main$ (RUNNING)

Found an active job.

Waiting for job to finish...
Waiting for response...
------------------ Running/Restarting Jobs -------------------
30.05.2020 07:11:24 : 3d40ed91bc55f4d199d2d3f44b6c549f : com.xxx.yyy.zzz.streaming.Main$ (RESTARTING)
--------------------------------------------------------------
No scheduled jobs.
30.05.2020 07:11:24 : 3d40ed91bc55f4d199d2d3f44b6c549f : com.xxx.yyy.zzz.streaming.Main$ (RUNNING)

Found an active job.

Waiting for job to finish...
Waiting for response...
------------------ Running/Restarting Jobs -------------------
30.05.2020 07:11:24 : 3d40ed91bc55f4d199d2d3f44b6c549f : com.xxx.yyy.zzz.streaming.Main$ (RESTARTING)
--------------------------------------------------------------
No scheduled jobs.

Unknown job state, exiting 3
```

Under what circumstances does this error occur? How can I find out more information about its causes?

**Comment by laughingman7743** [comment]
I'm running a streaming job with the following configuration to output Savepoints to GCS.

```yaml
savepointsDir: gs://my-bucket/path/to/savepoints/
autoSavepointSeconds: 300
restartPolicy: FromSavepointOnFailure
```

The following Docker image with gcs-connector installed is used.

https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/images/flink/README.md


When I start FlinkCluster with `kubectl apply -f my-flink-cluster.yaml`, it starts without problems and Savepoints are written to GCS.
However, if `Unknown job state, exiting 3` occurs and the job is restarted from Savepoints, the following error occurs and the job does not start.

```
java.lang.NoClassDefFoundError: com/google/cloud/hadoop/gcsio/GoogleCloudStorageImpl$3
    at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.open(GoogleCloudStorageImpl.java:660)
    at com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.open(GoogleCloudStorageFileSystem.java:277)
    at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFSInputStream.<init>(GoogleHadoopFSInputStream.java:78)
    at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.open(GoogleHadoopFileSystemBase.java:620)
    at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:787)
    at org.apache.flink.runtime.fs.hdfs.HadoopFileSystem.open(HadoopFileSystem.java:120)
    at org.apache.flink.runtime.fs.hdfs.HadoopFileSystem.open(HadoopFileSystem.java:37)
    at org.apache.flink.core.fs.SafetyNetWrapperFileSystem.open(SafetyNetWrapperFileSystem.java:85)
    at org.apache.flink.runtime.state.filesystem.FileStateHandle.openInputStream(FileStateHandle.java:68)
    at org.apache.flink.runtime.state.OperatorStreamStateHandle.openInputStream(OperatorStreamStateHandle.java:66)
    at org.apache.flink.runtime.state.OperatorStateRestoreOperation.restore(OperatorStateRestoreOperation.java:73)
    at org.apache.flink.runtime.state.DefaultOperatorStateBackendBuilder.build(DefaultOperatorStateBackendBuilder.java:83)
    at org.apache.flink.contrib.streaming.state.RocksDBStateBackend.createOperatorStateBackend(RocksDBStateBackend.java:565)
    at org.apache.flink.streaming.api.operators.StreamTaskStateInitializerImpl.lambda$operatorStateBackend$0(StreamTaskStateInitializerImpl.java:243)
    at org.apache.flink.streaming.api.operators.BackendRestorerProcedure.attemptCreateAndRestore(BackendRestorerProcedure.java:142)
    at org.apache.flink.streaming.api.operators.BackendRestorerProcedure.createAndRestore(BackendRestorerProcedure.java:121)
    at org.apache.flink.streaming.api.operators.StreamTaskStateInitializerImpl.operatorStateBackend(StreamTaskStateInitializerImpl.java:252)
    at org.apache.flink.streaming.api.operators.StreamTaskStateInitializerImpl.streamOperatorStateContext(StreamTaskStateInitializerImpl.java:139)
    at org.apache.flink.streaming.api.operators.AbstractStreamOperator.initializeState(AbstractStreamOperator.java:255)
    at org.apache.flink.streaming.runtime.tasks.StreamTask.initializeStateAndOpen(StreamTask.java:989)
    at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$0(StreamTask.java:453)
    at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:94)
    at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:448)
    at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:460)
    at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:708)
    at org.apache.flink.runtime.taskmanager.Task.run(Task.java:533)
    at java.lang.Thread.run(Thread.java:748)
```

I am investigating the cause.

**Comment by functicons** [comment]
Thanks for the bug report!

1) Regarding the `Unknown job state, exiting 3`, I think what happened was that there was a task failure and Flink was trying to restart/recover it and other affected tasks, see this [doc](https://ci.apache.org/projects/flink/flink-docs-stable/dev/task_failure_recovery.html) for more details. But unfortunately, the operator didn't handle `RESTARTING` status and exited with 3. I think the fix is to add RESTARTING and treat it as RUNNING [here](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/0b10a81e5e933fa4799c4da7f3c8b123601d1646/controllers/flinkcluster_submit_job_script.go#L88). Also, it might be a better strategy to wait for a while (e.g., 5 minutes) before exiting when encountering unknown state.

2) Regarding the `NoClassDefFoundError` issue, I don't have any idea at this point. Let me know if you have new findings.

The fix to issue 1 should be easy, I can push a PR, but I hope you can help verify / test. I you can fix it by yourself and want to contribute to the project, I welcome you send me a PR. What do you think?

**Comment by laughingman7743** [comment]
Thank you for the details of the error.
I created a PR. I would appreciate a review. 🙏 
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/253

**Comment by laughingman7743** [comment]
I think the `NoClassDefFoundError` needs to be investigated more. I'll let you know if I learn anything more.

**Comment by laughingman7743** [comment]
NoClassDefFoundError I will register another issue when I find out more.

**Comment by functicons** [comment]
Thanks! Please let me know if you have verified the fix for unknown state worked.

**Comment by laughingman7743** [comment]
I've built a Docker image and I'm running it, so far there seems to be no problem. 😄

**Comment by laughingman7743** [comment]
About 17 hours later, `Unknown job state, exiting 3` occurred and the job was terminated.
```
Waiting for job to finish...
Waiting for response...
------------------ Running/Restarting Jobs -------------------
02.06.2020 09:05:00 : d11bc02db43da1799aca8b46eea81833 : xxx.yyy.zzz.Main$ (RUNNING)
--------------------------------------------------------------
No scheduled jobs.
02.06.2020 09:05:00 : d11bc02db43da1799aca8b46eea81833 : xxx.yyy.zzz.Main$ (RUNNING)

Found an active job.

Waiting for job to finish...
Waiting for response...
------------------ Running/Restarting Jobs -------------------
02.06.2020 09:05:00 : d11bc02db43da1799aca8b46eea81833 : xxx.yyy.zzz.Main$ (RUNNING)
--------------------------------------------------------------
No scheduled jobs.
02.06.2020 09:05:00 : d11bc02db43da1799aca8b46eea81833 : xxx.yyy.zzz.Main$ (RUNNING)

Found an active job.

Waiting for job to finish...
Waiting for response...
------------------ Running/Restarting Jobs -------------------
02.06.2020 09:05:00 : d11bc02db43da1799aca8b46eea81833 : xxx.yyy.zzz.Main$ (RUNNING)
--------------------------------------------------------------
No scheduled jobs.

Unknown job state, exiting 3
```
The cause is unknown. I can't run it for long periods of time. 😢

**Comment by functicons** [comment]
Is it possible that the command failed, as I mentioned last time, we shouldn't exit on unknown state, instead just ignore it and check it again in the next iteration.

**Comment by laughingman7743** [comment]
Yes, it's possible that the command failed for one reason or another.
Would the following modifications be a good idea?
```bash
function wait_for_job() {
	while true; do
		echo -e "\nWaiting for job to finish..."
		list_jobs

		# Find active job first.
		# If the current job is restarted by the operator, there will be records of past stopped jobs.
		# TODO: It needs to be improved to determine the job state with the submitted job id.
		if list_jobs | grep -e "(SCHEDULED)" -e "(RUNNING)"; then
			echo -e "\nFound an active job."
		else
			if list_jobs | grep "(FINISHED)"; then
				echo -e "\nJob has completed successfully, exiting 0"
				return 0
			fi
			if list_jobs | grep "(FAILED)"; then
				echo -e "\nJob failed, exiting 1"
				return 1
			fi
			if list_jobs | grep "(CANCELED)"; then
				echo -e "\nJob has been cancelled, exiting 2"
				return 2
			fi
			echo -e "\nUnknown job state, check it again in the next iteration."
		fi
		sleep 30
	done
}
```

**Comment by functicons** [comment]
Thanks for the PR! Let me know how it goes in your test.

**Comment by laughingman7743** [comment]
Jobs are no longer restarted with unknown statuses and can now run for longer than a day. 👍 
Thank you!

**Comment by laughingman7743** [comment]
The following error occurred:
```
------------------ Running/Restarting Jobs -------------------
05.06.2020 09:32:25 : 0c7750fbe9e516ba0d72ab8a1999e30b : xxx.yyy.zzz.Main$ (RUNNING)
--------------------------------------------------------------
No scheduled jobs.
05.06.2020 09:32:25 : 0c7750fbe9e516ba0d72ab8a1999e30b : xxx.yyy.zzz.Main$ (RUNNING)

Found an active job.

Waiting for job to finish...
Waiting for response...

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.util.FlinkException: Failed to retrieve job list.
        at org.apache.flink.client.cli.CliFrontend.listJobs(CliFrontend.java:355)
        at org.apache.flink.client.cli.CliFrontend.lambda$list$0(CliFrontend.java:337)
        at org.apache.flink.client.cli.CliFrontend.runClusterAction(CliFrontend.java:841)
        at org.apache.flink.client.cli.CliFrontend.list(CliFrontend.java:334)
        at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:896)
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:966)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
        at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:966)
Caused by: org.apache.flink.runtime.concurrent.FutureUtils$RetryException: Could not complete the operation. Number of retries has been exhausted.
        at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$8(FutureUtils.java:284)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
        at org.apache.flink.runtime.rest.RestClient.lambda$submitRequest$1(RestClient.java:342)
        at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
        at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)
        at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)
        at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
        at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
        at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531)
        at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111)
        at org.apache.flink.shaded.netty4.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:265)
        at org.apache.flink.shaded.netty4.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at org.apache.flink.shaded.netty4.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
        at org.apache.flink.shaded.netty4.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at org.apache.flink.shaded.netty4.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
        at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
        at org.apache.flink.shaded.netty4.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
        at org.apache.flink.shaded.netty4.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CompletionException: org.apache.flink.shaded.netty4.io.netty.channel.ConnectTimeoutException: connection timed out: xxx-yyy-zzz-jobmanager/1.2.3.4:8081
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
        at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:957)
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
        ... 19 more
Caused by: org.apache.flink.shaded.netty4.io.netty.channel.ConnectTimeoutException: connection timed out: xxx-yyy-zzz-jobmanager/1.2.3.4:8081
        at org.apache.flink.shaded.netty4.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
        ... 8 more
Waiting for response...
No running jobs.
No scheduled jobs.

Unknown job state, check it again in the next iteration.

Waiting for job to finish...
Waiting for response...
No running jobs.
No scheduled jobs.

Unknown job state, check it again in the next iteration.

Waiting for job to finish...
Waiting for response...
No running jobs.
No scheduled jobs.

Unknown job state, check it again in the next iteration.

Waiting for job to finish...

------------------------------------------------------------
 The program finished with the following exception:

java.lang.RuntimeException: Couldn't retrieve standalone cluster
	at org.apache.flink.client.deployment.StandaloneClusterDescriptor.lambda$retrieve$0(StandaloneClusterDescriptor.java:53)
	at org.apache.flink.client.cli.CliFrontend.runClusterAction(CliFrontend.java:840)
	at org.apache.flink.client.cli.CliFrontend.list(CliFrontend.java:334)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:896)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:966)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
	at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:966)
Caused by: java.net.UnknownHostException: xxx-yyy-zzz-jobmanager
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at java.net.InetAddress.getByName(InetAddress.java:1077)
	at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.getWebMonitorAddress(HighAvailabilityServicesUtils.java:201)
	at org.apache.flink.runtime.highavailability.HighAvailabilityServicesUtils.createClientHAService(HighAvailabilityServicesUtils.java:146)
	at org.apache.flink.client.program.rest.RestClusterClient.<init>(RestClusterClient.java:161)
	at org.apache.flink.client.deployment.StandaloneClusterDescriptor.lambda$retrieve$0(StandaloneClusterDescriptor.java:51)
	... 9 more
Waiting for response...
No running jobs.
No scheduled jobs.

Unknown job state, check it again in the next iteration.

Waiting for job to finish...
Waiting for response...
No running jobs.
No scheduled jobs.
```

TaskManager seems to have automatically restarted, but the job is not recovered with an unknown job status.
```
Unknown job state, check it again in the next iteration.

Waiting for job to finish...
Waiting for response...
No running jobs.
No scheduled jobs.
```
What do you know about it?

**Comment by functicons** [comment]
Can you check in the Flink web UI to see if there is any job and it status? I expect in this case the script should be able to see Failed job instead of no jobs or unknown job state.

**Comment by laughingman7743** [comment]
I checked in the webUI and the job is not running.

**Comment by laughingman7743** [comment]
The API response is below.
```
Waiting for response...
No running jobs.
No scheduled jobs.
```
Is it likely to require handling in the case of `No running jobs`?

**Comment by laughingman7743** [comment]
```
else
	if list_jobs | grep "(FINISHED)"; then
		echo -e "\nJob has completed successfully, exiting 0"
		return 0
	fi
	if list_jobs | grep "(FAILED)"; then
		echo -e "\nJob failed, exiting 1"
		return 1
	fi
	if list_jobs | grep "(CANCELED)"; then
		echo -e "\nJob has been cancelled, exiting 2"
		return 2
	fi
	if list_jobs | grep "No running jobs"; then
		echo -e "\nNo running jobs, exiting 3"
		return 3
	fi
	echo -e "\nUnknown job state, check it again in the next iteration."
fi
```

**Comment by functicons** [comment]
The root cause seems to be that JobManager was restarted:

```
java.net.UnknownHostException: xxx-yyy-zzz-jobmanager
```

Then the job got lost. In this case, we need to exit and let the operator to restart the job (if policy allows). We need to check both "No running jobs" and "No scheduled jobs".

**Comment by laughingman7743** [comment]
Ok, I see. I've fixed it, please review it. 🙏 
https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/pull/262

**Comment by functicons** [comment]
Thanks! Let me know how it goes in your test.

**Comment by laughingman7743** [comment]
```
------------------ Running/Restarting Jobs -------------------
08.06.2020 03:07:52 : b617ae746e8bd9c71376f945752ea7b6 : xxx.yyy.zzz.Main$ (RUNNING)
--------------------------------------------------------------
No scheduled jobs.
08.06.2020 03:07:52 : b617ae746e8bd9c71376f945752ea7b6 : xxx.yyy.zzz.Main$ (RUNNING)

Found an active job.

Waiting for job to finish...
Waiting for response...
------------------ Running/Restarting Jobs -------------------
08.06.2020 03:07:52 : b617ae746e8bd9c71376f945752ea7b6 : xxx.yyy.zzz.Main$ (RUNNING)
--------------------------------------------------------------
No scheduled jobs.
08.06.2020 03:07:52 : b617ae746e8bd9c71376f945752ea7b6 : xxx.yyy.zzz.Main$ (RUNNING)

Found an active job.

Waiting for job to finish...
Waiting for response...

------------------------------------------------------------
 The program finished with the following exception:

org.apache.flink.util.FlinkException: Failed to retrieve job list.
	at org.apache.flink.client.cli.CliFrontend.listJobs(CliFrontend.java:355)
	at org.apache.flink.client.cli.CliFrontend.lambda$list$0(CliFrontend.java:337)
	at org.apache.flink.client.cli.CliFrontend.runClusterAction(CliFrontend.java:841)
	at org.apache.flink.client.cli.CliFrontend.list(CliFrontend.java:334)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:896)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:966)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
	at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:966)
Caused by: org.apache.flink.runtime.concurrent.FutureUtils$RetryException: Could not complete the operation. Number of retries has been exhausted.
	at org.apache.flink.runtime.concurrent.FutureUtils.lambda$retryOperationWithDelay$8(FutureUtils.java:284)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at org.apache.flink.runtime.rest.RestClient.lambda$submitRequest$1(RestClient.java:342)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111)
	at org.apache.flink.shaded.netty4.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:265)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at org.apache.flink.shaded.netty4.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at org.apache.flink.shaded.netty4.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.CompletionException: org.apache.flink.shaded.netty4.io.netty.channel.ConnectTimeoutException: connection timed out: flinkcluster-xxx-yyy-zzz-jobmanager/1.2.3.4:8081
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:957)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
	... 19 more
Caused by: org.apache.flink.shaded.netty4.io.netty.channel.ConnectTimeoutException: connection timed out: flinkcluster-xxx-yyy-zzz-jobmanager/1.2.3.4:8081
	at org.apache.flink.shaded.netty4.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
	... 8 more
Waiting for response...
No running jobs.
No scheduled jobs.
No running jobs.
No scheduled jobs.

No running and scheduled jobs, exiting 3
```
It seems to be working perfectly. I are also able to confirm that I am able to start a new job after this.
Thank you very much. 🙇
