### ISSUE TITLE
make deploy failed panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by danxian-baiheng** [GoogleCloudPlatform/flink-on-k8s-operator#322]
output text:
```
+ kubectl get secret webhook-server-cert -n flink-operator-system
+ echo 'Secret webhook-server-cert already exists.'
Secret webhook-server-cert already exists.
+ exit 0
rm -rf config/deploy && cp -rf config/default config/deploy && cd config/deploy \
		&& kustomize edit set nameprefix flink-operator- \
		&& kustomize edit set namespace flink-operator-system
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/kustfile.(*kustomizationFile).parseCommentedFields(0xc0005b3140, 0xc0006f3200, 0x888, 0x900, 0x3, 0x3)
	/root/baiheng/flink-operator/kustomize/kustomize/internal/commands/kustfile/kustomizationfile.go:205 +0x7b6
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/kustfile.(*kustomizationFile).Read(0xc0005b3140, 0x3244fa8, 0xc0005b3140, 0x0)
	/root/baiheng/flink-operator/kustomize/kustomize/internal/commands/kustfile/kustomizationfile.go:162 +0x2a8
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/edit/set.(*setNamePrefixOptions).RunSetNamePrefix(0xc00007e8a0, 0x242f820, 0x3244fa8, 0xdac400, 0xc0005a3d80)
	/root/baiheng/flink-operator/kustomize/kustomize/internal/commands/edit/set/set_name_prefix.go:58 +0x5f
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/edit/set.newCmdSetNamePrefix.func1(0xc00009db80, 0xc00007f510, 0x1, 0x1, 0x0, 0x0)
	/root/baiheng/flink-operator/kustomize/kustomize/internal/commands/edit/set/set_name_prefix.go:36 +0x85
github.com/spf13/cobra.(*Command).execute(0xc00009db80, 0xc00007f4d0, 0x1, 0x1, 0xc00009db80, 0xc00007f4d0)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001662c0, 0x9, 0x241d820, 0xc00000f220)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/root/baiheng/flink-operator/kustomize/kustomize/main.go:23 +0x73
make: *** [build-overlay] Error 2
```
what happened?
is there any problem with Kustomize or Flink operator?

**Comment by functicons** [comment]
Did you simply run `make deploy`?
